newline_style = "Unix"
edition = "2021"
use_field_init_shorthand = true
use_try_shorthand = true
max_width = 80

# Unstable features below
error_on_unformatted = false
version = "Two"
comment_width = 100
error_on_line_overflow = true
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = false
imports_granularity = "Module"
group_imports = "StdExternalCrate"
normalize_doc_attributes = true
wrap_comments = true
